"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

type Profile={id:string;email:string;full_name:string;role:"admin"|"member";status:"pending"|"approved"|"removed"};
type Post={id:number;title:string;description:string;category:string;image_url:string|null;status:string;created_at:string;profiles:{full_name:string}|null};
const categories=["news","history","photos","learning","events"];
const sections=[["home","⌂","Home"],["news","◈","News"],["history","◷","History"],["photos","▣","Photos"],["learning","◇","Learning"],["events","○","Events"],["submit","+","Submit a post"],["admin","⚙","Administration"]] as const;

export default function FamilyApp(){
  const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[posts,setPosts]=useState<Post[]>([]),[members,setMembers]=useState<Profile[]>([]),[pendingPosts,setPendingPosts]=useState<Post[]>([]),[view,setView]=useState("home"),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=useCallback(async(current:User)=>{
    const {data:p,error:pe}=await supabase.from("profiles").select("*").eq("id",current.id).single();
    if(pe)throw pe;setProfile(p);
    if(p.status==="approved"){
      const {data:approved,error:ae}=await supabase.from("posts").select("*,profiles!posts_author_id_fkey(full_name)").eq("status","approved").order("created_at",{ascending:false});
      if(ae)throw ae;setPosts(approved||[]);
      if(p.role==="admin"){
        const [{data:allMembers,error:me},{data:queue,error:qe}]=await Promise.all([
          supabase.from("profiles").select("*").order("created_at"),
          supabase.from("posts").select("*,profiles!posts_author_id_fkey(full_name)").eq("status","pending").order("created_at")
        ]);if(me)throw me;if(qe)throw qe;setMembers(allMembers||[]);setPendingPosts(queue||[]);
      }
    }
  },[]);
  useEffect(()=>{supabase.auth.getUser().then(async({data})=>{setUser(data.user);if(data.user)await load(data.user);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)});const {data:s}=supabase.auth.onAuthStateChange((_e,session)=>{setUser(session?.user||null);if(!session)setProfile(null)});return()=>s.subscription.unsubscribe()},[load]);
  const shown=useMemo(()=>view==="home"?posts:posts.filter(p=>p.category===view),[posts,view]);
  async function refresh(){if(user)await load(user)}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=e.currentTarget,v=Object.fromEntries(new FormData(f));const {error:x}=await supabase.from("posts").insert({title:String(v.title).trim(),description:String(v.description).trim(),category:v.category,image_url:String(v.image_url).trim()||null,author_id:user!.id});if(x){setError(x.message);return}f.reset();setMessage("Your post is waiting for administrator approval.");await refresh()}
  async function update(table:"profiles"|"posts",id:string|number,values:Record<string,string>){setError("");const {error:x}=await supabase.from(table).update(values).eq("id",id);if(x){setError(x.message);return}setMessage("The change was saved.");await refresh()}
  if(loading)return <div className="loading">Opening the family website…</div>;
  if(!user)return <Auth/>;
  if(!profile)return <Status title="Account setup is incomplete" text="Please refresh the page. If this continues, the database setup has not been completed yet."/>;
  if(profile.status!=="approved")return <Status title="Account awaiting approval" text="Karnell or Bahaiz must approve your family account before you can view private content."><button className="secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></Status>;
  const isAdmin=profile.role==="admin",heading=view==="home"?`Welcome, ${profile.full_name.split(" ")[0]}`:sections.find(s=>s[0]===view)?.[2]||"Family Website";
  return <div className="shell"><header className="topbar"><div className="brand"><div className="crest">F</div><div><strong>Family Website</strong><small>Our people. Our story.</small></div></div><div className="account"><span>{profile.email}</span><button className="signout" style={{background:"transparent"}} onClick={()=>supabase.auth.signOut()}>Sign out</button></div></header><div className="layout"><aside className="sidebar"><p className="nav-label">Family spaces</p><nav className="nav">{sections.filter(s=>s[0]!=="admin"||isAdmin).map(([k,i,l])=><button key={k} className={view===k?"active":""} onClick={()=>{setView(k);setMessage("");setError("")}}><span className="icon">{i}</span>{l}</button>)}</nav></aside><main className="main"><section className="hero"><div><p className="eyebrow">Private family community</p><h1>{heading}</h1><p>{view==="home"?"A protected place to keep up with family, preserve our history, learn together, and celebrate what matters.":view==="admin"?"Approve accounts, review posts, and manage administrator roles.":view==="submit"?"Share something meaningful with the family. Every post is reviewed before it appears.":`Approved ${heading.toLowerCase()} shared by our family.`}</p></div>{view!=="submit"&&<button className="primary" onClick={()=>setView("submit")}>+ Submit a post</button>}</section>{message&&<div className="notice">{message}</div>}{error&&<div className="notice error">{error}</div>}{view==="submit"?<PostForm submit={submit}/>:view==="admin"&&isAdmin?<Admin members={members} queue={pendingPosts} current={profile} update={update}/>:<Content posts={shown} view={view} heading={heading} navigate={setView}/>}</main></div></div>
}

function Auth(){const [mode,setMode]=useState<"signin"|"signup">("signin"),[message,setMessage]=useState(""),[error,setError]=useState("");async function act(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const v=Object.fromEntries(new FormData(e.currentTarget)),email=String(v.email),password=String(v.password);if(mode==="signup"){const {error:x}=await supabase.auth.signUp({email,password,options:{data:{full_name:String(v.full_name)}}});if(x)setError(x.message);else setMessage("Account created. Check your email if confirmation is enabled, then sign in.")}else{const {error:x}=await supabase.auth.signInWithPassword({email,password});if(x)setError(x.message)}}return <div className="pending" style={{maxWidth:480,textAlign:"left"}}><div className="seal">F</div><p className="eyebrow">Private family space</p><h1>{mode==="signin"?"Welcome back":"Create an account"}</h1><p>{mode==="signin"?"Sign in with your family website account.":"Create an account. An administrator must approve it before you can view family content."}</p>{message&&<div className="notice">{message}</div>}{error&&<div className="notice error">{error}</div>}<form className="form" onSubmit={act}>{mode==="signup"&&<Field label="Full name"><input name="full_name" required/></Field>}<Field label="Email"><input name="email" type="email" required/></Field><Field label="Password"><input name="password" type="password" minLength={8} required/></Field><button className="primary">{mode==="signin"?"Sign in":"Create account"}</button></form><button className="secondary" style={{marginTop:12,width:"100%"}} onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"Create a family account":"I already have an account"}</button></div>}
function Status({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="pending"><div className="seal">⌛</div><p className="eyebrow">Private family space</p><h1>{title}</h1><p>{text}</p>{children}</div>}
function PostForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <section className="panel" style={{maxWidth:760}}><div className="panel-head"><h2>Submit a family post</h2><span className="pill">Review required</span></div><form className="form" onSubmit={submit}><Field label="Title *"><input name="title" maxLength={100} required/></Field><Field label="Family page *"><select name="category" required defaultValue=""><option value="" disabled>Select a page</option>{categories.map(c=><option key={c} value={c}>{cap(c)}</option>)}</select></Field><Field label="Description *"><textarea name="description" maxLength={2000} required/></Field><Field label="Photograph link (optional)"><input name="image_url" type="url" placeholder="https://…"/></Field><button className="primary">Send for approval</button></form></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Admin({members,queue,current,update}:{members:Profile[];queue:Post[];current:Profile;update:(t:"profiles"|"posts",id:string|number,v:Record<string,string>)=>void}){return <div className="grid"><section className="panel"><div className="panel-head"><h2>Post review queue</h2><span className="pill">{queue.length} pending</span></div><div className="queue">{queue.length?queue.map(p=><article className="post" key={p.id}><div className="post-meta"><span className="pill">{p.category}</span><span>{p.profiles?.full_name}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="actions"><button className="primary" onClick={()=>update("posts",p.id,{status:"approved"})}>Approve</button><button className="danger" onClick={()=>update("posts",p.id,{status:"rejected"})}>Reject</button></div></article>):<Empty text="No posts are waiting."/>}</div></section><section className="panel"><h2>Family accounts</h2><div className="queue" style={{marginTop:18}}>{members.map(m=><div className="member-row" key={m.id}><div><strong>{m.full_name}</strong><small>{m.email} · {m.status} · {m.role}</small></div><div className="actions">{m.status==="pending"&&<button className="primary" onClick={()=>update("profiles",m.id,{status:"approved"})}>Approve</button>}{m.status==="approved"&&m.role==="member"&&<button className="secondary" onClick={()=>update("profiles",m.id,{role:"admin"})}>Make admin</button>}{m.id!==current.id&&<button className="danger" onClick={()=>update("profiles",m.id,{status:"removed"})}>Remove</button>}</div></div>)}</div></section></div>}
function Content({posts,view,heading,navigate}:{posts:Post[];view:string;heading:string;navigate:(x:string)=>void}){return <div className="grid"><section className="panel"><div className="panel-head"><h2>{view==="home"?"Latest from the family":heading}</h2><span className="pill">{posts.length} posts</span></div><div className="post-list">{posts.length?posts.map(p=><article className="post" key={p.id}><div className="post-meta"><span className="pill">{p.category}</span><span>{p.profiles?.full_name}</span><time>{new Date(p.created_at).toLocaleDateString()}</time></div><h3>{p.title}</h3><p>{p.description}</p>{p.image_url&&<img src={p.image_url} alt="Family post photograph"/>}</article>):<Empty text="Nothing has been shared here yet."/>}</div></section><aside className="panel"><h2>Family spaces</h2><div className="categories">{categories.map(c=><button key={c} className="category" style={{borderLeft:0,borderRight:0,borderTop:0,background:"transparent",width:"100%"}} onClick={()=>navigate(c)}><span>{cap(c)}</span><span>→</span></button>)}</div></aside></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function cap(x:string){return x[0].toUpperCase()+x.slice(1)}
