"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Member = { email:string; name:string; role:"admin"|"member"; status:"pending"|"approved"|"removed" };
type Post = { id:number; title:string; description:string; category:string; imageUrl:string|null; authorName:string; status:string; createdAt:string };
type Dashboard = { member:Member; posts:Post[]; pendingPosts:Post[]; pendingMembers:Member[]; approvedMembers:Member[] };
const categories=["news","history","photos","learning","events"];
const sections = [["home","⌂","Home"],["news","◈","News"],["history","◷","History"],["photos","▣","Photos"],["learning","◇","Learning"],["events","○","Events"],["submit","+","Submit a post"],["admin","⚙","Administration"]] as const;

export default function FamilyPortal({user,signOutPath}:{user:{name:string;email:string};signOutPath:string}) {
  const [data,setData]=useState<Dashboard|null>(null),[view,setView]=useState("home"),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/dashboard",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load the family website.");setData(b)},[]);
  useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
  const posts=useMemo(()=>view==="home"?data?.posts??[]:(data?.posts??[]).filter(p=>p.category===view),[data,view]);

  if(error&&!data)return <Status icon="!" title="Something went wrong" text={error}><button className="primary" onClick={()=>location.reload()}>Try again</button></Status>;
  if(!data)return <div className="loading">Opening the family website…</div>;
  if(data.member.status!=="approved")return <Status icon="⌛" title="Account awaiting approval" text="Your secure sign-in worked. Karnell or Bahaiz must approve your family account before you can view private content."><p className="help">Signed in as {user.email}</p><a className="signout" style={{color:"var(--forest)",display:"inline-block",marginTop:18}} href={signOutPath}>Sign out</a></Status>;

  const isAdmin=data.member.role==="admin";
  const visibleSections=sections.filter(s=>s[0]!=="admin"||isAdmin);
  const heading=view==="home"?`Welcome, ${data.member.name.split(" ")[0]}`:sections.find(s=>s[0]===view)?.[2]??"Family Website";

  async function submitPost(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");setError("");const form=e.currentTarget;const r=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const b=await r.json();if(!r.ok){setError(b.error||"Post could not be submitted.");return}form.reset();setMessage("Your post was submitted and is waiting for administrator approval.");await load()}
  async function adminAction(kind:string,id:number|string,value:string){setMessage("");setError("");const r=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({kind,id,value})});const b=await r.json();if(!r.ok){setError(b.error||"The change could not be saved.");return}setMessage("The change was saved.");await load()}

  return <div className="shell">
    <header className="topbar"><div className="brand"><div className="crest">F</div><div><strong>Family Website</strong><small>Our people. Our story.</small></div></div><div className="account"><span>{user.email}</span><a className="signout" href={signOutPath}>Sign out</a></div></header>
    <div className="layout"><aside className="sidebar"><p className="nav-label">Family spaces</p><nav className="nav" aria-label="Family website navigation">{visibleSections.map(([key,icon,label])=><button key={key} className={view===key?"active":""} onClick={()=>{setView(key);setMessage("");setError("")}}><span className="icon">{icon}</span>{label}</button>)}</nav></aside>
      <main className="main"><section className="hero"><div><p className="eyebrow">Private family community</p><h1>{heading}</h1><p>{view==="home"?"A protected place to keep up with family, preserve our history, learn together, and celebrate what matters.":view==="submit"?"Share something meaningful with the family. Every post is reviewed before it appears.":view==="admin"?"Approve family accounts and review submitted content.":`Approved ${heading.toLowerCase()} shared by our family.`}</p></div>{view!=="submit"&&<button className="primary" onClick={()=>setView("submit")}>+ Submit a post</button>}</section>
        {message&&<div className="notice" role="status">{message}</div>}{error&&<div className="notice error" role="alert">{error}</div>}
        {view==="home"&&<div className="stats"><Stat value={data.posts.length} label="Approved family posts"/><Stat value={new Set(data.posts.map(p=>p.category)).size} label="Active family spaces"/><Stat value={isAdmin?data.pendingPosts.length:"✓"} label={isAdmin?"Posts awaiting review":"Account approved"}/></div>}
        {view==="submit"?<PostForm onSubmit={submitPost}/>:view==="admin"&&isAdmin?<Admin data={data} action={adminAction}/>:<Content posts={posts} view={view} heading={heading} navigate={setView}/>} 
      </main></div>
  </div>;
}

function Status({icon,title,text,children}:{icon:string;title:string;text:string;children:React.ReactNode}){return <div className="pending"><div className="seal">{icon}</div><p className="eyebrow">Private family space</p><h1>{title}</h1><p>{text}</p>{children}</div>}
function Stat({value,label}:{value:number|string;label:string}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function PostForm({onSubmit}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <section className="panel" style={{maxWidth:760}}><div className="panel-head"><h2>Submit a family post</h2><span className="pill">Review required</span></div><form className="form" onSubmit={onSubmit}><Field label="Title *"><input id="title" name="title" maxLength={100} required/></Field><Field label="Family page *"><select id="category" name="category" required defaultValue=""><option value="" disabled>Select a page</option>{categories.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select></Field><Field label="Description *"><textarea id="description" name="description" maxLength={2000} required/></Field><Field label="Photograph link (optional)"><input id="imageUrl" name="imageUrl" type="url" placeholder="https://…"/><span className="help">Photograph uploads will be added after the family confirms its photo and consent rules.</span></Field><button className="primary" type="submit">Send for approval</button></form></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Admin({data,action}:{data:Dashboard;action:(kind:string,id:number|string,value:string)=>void}){return <div className="grid"><section className="panel"><div className="panel-head"><h2>Post review queue</h2><span className="pill">{data.pendingPosts.length} pending</span></div><div className="queue">{data.pendingPosts.length===0?<Empty text="No posts are waiting for review."/>:data.pendingPosts.map(p=><article className="post" key={p.id}><div className="post-meta"><span className="pill">{p.category}</span><span>Submitted by {p.authorName}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="actions"><button className="primary" onClick={()=>action("post",p.id,"approved")}>Approve</button><button className="danger" onClick={()=>action("post",p.id,"rejected")}>Reject</button></div></article>)}</div></section><section className="queue"><div className="panel"><div className="panel-head"><h2>Account requests</h2><span className="pill">{data.pendingMembers.length} pending</span></div><div className="queue">{data.pendingMembers.length===0?<Empty text="No accounts are waiting."/>:data.pendingMembers.map(m=><div className="member-row" key={m.email}><div><strong>{m.name}</strong><small>{m.email}</small></div><div className="actions"><button className="primary" onClick={()=>action("member",m.email,"approved")}>Approve</button><button className="danger" onClick={()=>action("member",m.email,"removed")}>Remove</button></div></div>)}</div></div><div className="panel"><div className="panel-head"><h2>Approved accounts</h2><span className="pill">{data.approvedMembers.length}</span></div><div className="queue">{data.approvedMembers.map(m=><div className="member-row" key={m.email}><div><strong>{m.name}</strong><small>{m.email} · {m.role}</small></div>{m.role==="admin"?<button className="secondary" disabled={m.email===data.member.email} onClick={()=>action("role",m.email,"member")}>{m.email===data.member.email?"You":"Make member"}</button>:<button className="secondary" onClick={()=>action("role",m.email,"admin")}>Make administrator</button>}</div>)}</div></div></section></div>}
function Content({posts,view,heading,navigate}:{posts:Post[];view:string;heading:string;navigate:(x:string)=>void}){return <div className="grid"><section className="panel"><div className="panel-head"><h2>{view==="home"?"Latest from the family":heading}</h2><span className="pill">{posts.length} posts</span></div><div className="post-list">{posts.length===0?<Empty text="Nothing has been shared here yet. Be the first to submit a post."/>:posts.map(p=><article className="post" key={p.id}><div className="post-meta"><span className="pill">{p.category}</span><span>{p.authorName}</span><span>•</span><time>{new Date(p.createdAt).toLocaleDateString()}</time></div><h3>{p.title}</h3><p>{p.description}</p>{p.imageUrl&&<img src={p.imageUrl} alt="Family post photograph"/>}</article>)}</div></section><aside className="panel"><h2>Family spaces</h2><div className="categories">{categories.map(c=><button key={c} className="category" style={{borderLeft:0,borderRight:0,borderTop:0,background:"transparent",cursor:"pointer",width:"100%"}} onClick={()=>navigate(c)}><span>{titleCase(c)}</span><span>→</span></button>)}</div></aside></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function titleCase(x:string){return x[0].toUpperCase()+x.slice(1)}
