-- Run this file once in the Supabase SQL Editor for an existing family website.

create table if not exists public.family_members (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 1 and 100),
  relationship_label text check (char_length(relationship_label) <= 60),
  branch text check (char_length(branch) <= 60),
  life_years text check (char_length(life_years) <= 40),
  bio text check (char_length(bio) <= 500),
  photo_url text,
  parent_id bigint references public.family_members(id) on delete set null,
  generation integer not null default 1 check (generation between 1 and 20),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.family_members enable row level security;

drop policy if exists "approved members read family tree" on public.family_members;
create policy "approved members read family tree" on public.family_members
for select to authenticated using (public.is_approved_family_member());

drop policy if exists "admins add family tree members" on public.family_members;
create policy "admins add family tree members" on public.family_members
for insert to authenticated with check (public.is_family_admin());

drop policy if exists "admins update family tree members" on public.family_members;
create policy "admins update family tree members" on public.family_members
for update to authenticated using (public.is_family_admin()) with check (public.is_family_admin());

drop policy if exists "admins remove family tree members" on public.family_members;
create policy "admins remove family tree members" on public.family_members
for delete to authenticated using (public.is_family_admin());

create index if not exists family_members_generation_idx
on public.family_members(generation,full_name);

create index if not exists family_members_parent_idx
on public.family_members(parent_id);
