-- Run this entire file once in the Supabase SQL Editor.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role text not null default 'member' check (role in ('admin','member')),
  status text not null default 'pending' check (status in ('pending','approved','removed')),
  created_at timestamptz not null default now()
);

create table public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 100),
  description text not null check (char_length(description) between 1 and 2000),
  category text not null check (category in ('news','history','photos','learning','events')),
  image_url text,
  author_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id)
);

create or replace function public.is_family_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin' and status='approved'); $$;

create or replace function public.is_approved_family_member()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from profiles where id=auth.uid() and status='approved'); $$;

create or replace function public.handle_new_family_user()
returns trigger language plpgsql security definer set search_path=public
as $$
declare first_account boolean;
begin
  select not exists(select 1 from profiles) into first_account;
  insert into profiles(id,email,full_name,role,status)
  values(new.id,new.email,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),split_part(new.email,'@',1)),
    case when first_account then 'admin' else 'member' end,
    case when first_account then 'approved' else 'pending' end);
  return new;
end;
$$;

create trigger create_family_profile after insert on auth.users
for each row execute function public.handle_new_family_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;

create policy "members read own profile or admins read all" on public.profiles
for select to authenticated using (id=auth.uid() or public.is_family_admin());

create policy "admins manage family profiles" on public.profiles
for update to authenticated using (public.is_family_admin()) with check (public.is_family_admin());

create policy "approved members read approved posts" on public.posts
for select to authenticated using (
  (status='approved' and public.is_approved_family_member()) or author_id=auth.uid() or public.is_family_admin()
);

create policy "approved members submit their own posts" on public.posts
for insert to authenticated with check (
  author_id=auth.uid() and status='pending' and public.is_approved_family_member()
);

create policy "admins review posts" on public.posts
for update to authenticated using (public.is_family_admin()) with check (public.is_family_admin());

create index posts_status_created_idx on public.posts(status,created_at desc);
create index profiles_status_idx on public.profiles(status);
